### ISSUE TITLE
AES example

### ISSUE THREAD

**Issue by xajik** [korlibs/krypto#38]
Hi, 

I face difficulties to use AES to encrypt/decrypt a string. Can you please provide an example? 
Example: "Hello World"

**Comment by soywiz** [comment]
I have just enabled GitHub discussions here: https://github.com/korlibs/krypto/discussions

AES works with `ByteArray` only because works at the octets level.

A character like `H` could be represented in many ways. Including ASCII and UTF-8 as `48` or in UTF-16 `00 48` or `48 00` and many others.

The way to do this is to convert that string into a `ByteArray` in a specific charset.

You can do that with:

```kotlin
val charset = UTF8
val originalString = "Hello World"

val originalUnencryptedBytes = originalString.toByteArray(charset)
val encyptedBytes = // do AES encryption with originalUnencryptedBytes
val unencryptedBytes = // do AES decryption with encyptedBytes
val unencryptedString = unencryptedBytes.toString(charset)

assertEquals(originalString, unencryptedString)
```

**Comment by 0rangeFox** [comment]
Hey, I'll make a quick example!

```kotlin
val originalString = "Hello World".toByteArray()
val key = "zsPC?wrecAvaQKved(@tv3Px&Bn'Lomi".toByteArray() // The key should be max 32 chars.

// Encrypt the string
val encryptedString = AES.encryptAesCbc(originalString, key, key /* or ByteArray(32) */, Padding.PKCS7Padding)
println(Hex.encode(encryptedString))

// Decrypt the string
val decryptedString = AES.decryptAesCbc(encryptedString, key, key /* or ByteArray(32) */, Padding.PKCS7Padding)
println(decryptedString.decodeToString())
```
