### ISSUE TITLE
Kotlin 1.3.40

### ISSUE THREAD

**Issue by felipehjcosta** [korlibs/krypto#7]
Hey!

Any plan to support Kotlin 1.3.40?

Thanks!

**Comment by felipehjcosta** [comment]
I opened a PR #8

**Comment by soywiz** [comment]
I was waiting for 1.3.50 that is likely to be released soon. But I am releasing 1.7.1 here: https://bintray.com/korlibs/korlibs/krypto

I tried to publish it to jcenter, but they rejected it because missing a -sources.jar, hopefully the new version of the plugin publishes that artifact and if it works, it will be published to jcenter as long as they accept it.

**Comment by felipehjcosta** [comment]
Thanks!
